apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
           limits:
            cpu: "100m"
            memory: "6Mi"
           requests:
            cpu: "100m"
            memory: "6Mi"
        ports:
        - containerPort: 80
   
