apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
      - name: tensorflow-container
        image: tensorflow/tensorflow:latest-gpu
        ports:
        - containerPort: 8888
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: 1
            memory: 4Gi

